<?php if (!Mage::getStoreConfig('yotpo/yotpo_general_group/disable_default_widget_position',Mage::app()->getStore())):?>
	<div class="yotpo yotpo-main-widget"
		data-product-id="<?php echo $this->getProductId() ?>"
		data-name="<?php echo $this->getProductName() ?>"
		data-url="<?php echo $this->getProductUrl() ?>"
		data-image-url="<?php echo $this->getProductImageUrl() ?>"
		data-description="<?php echo $this->getProductDescription() ?>">
	</div>
<?php endif ?>