<div class="yotpo reviews"
	data-appkey="<?php echo $this->getAppKey() ?>"
	data-domain="<?php echo $this->getDomain() ?>"
	data-product-id="<?php echo $this->getProductId() ?>"
	data-product-models="<?php echo $this->getProductModel() ?>"
	data-name="<?php echo $this->getProductName() ?>"
	data-url="<?php echo $this->getProductUrl() ?>"
	data-image-url="<?php echo $this->getProductImageUrl() ?>"
	data-description="<?php echo $this->getProductDescription() ?>"
	data-bread-crumbs="<?php echo $this->getProductBreadcrumbs() ?>">
</div>
